[2023-03-11 20:45:06,150]-[root]-[INFO]-[main_server.py:<module>():20 Line]:AiServer启动成功!
[2023-03-11 20:49:09,297]-[root]-[ERROR]-[main_server.py:<module>():24 Line]:Traceback (most recent call last):
  File "D:\tornado服务器\tornado_template\main_server.py", line 22, in <module>
    tornado.ioloop.IOLoop.instance().start()
  File "D:\Anaconda\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "D:\Anaconda\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\Anaconda\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Anaconda\lib\asyncio\base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "D:\Anaconda\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "D:\Anaconda\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

